# Generated by Django 3.1.5 on 2021-01-07 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_room',
            fields=[
                ('room_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('room_open', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='participant',
            fields=[
                ('participant_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('room_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chat_room')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('message_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('sent_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('room_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chat_room')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.participant')),
            ],
        ),
    ]
