# Generated by Django 3.1.5 on 2021-01-08 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0002_bid_bidding_like_on_sale_save'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_room',
            name='land_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lands.land'),
        ),
    ]
