# Generated by Django 3.1.5 on 2021-01-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_room_land_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_room',
            name='room_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
