# Generated by Django 3.1.5 on 2021-01-07 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='land',
            fields=[
                ('land_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(default='Land description')),
                ('likes', models.BigIntegerField(null=True)),
                ('size', models.CharField(max_length=100, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='land_owner',
            fields=[
                ('land_owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('land_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lands.land')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
