# Generated by Django 3.1.4 on 2021-01-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('Likes', models.IntegerField()),
                ('Location', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
                ('Negotiable', models.BooleanField(default=False)),
                ('Size', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
