# Generated by Django 3.1.4 on 2021-01-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='land',
            name='Likes',
        ),
        migrations.RemoveField(
            model_name='land',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='land',
            name='Negotiable',
        ),
        migrations.RemoveField(
            model_name='land',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='land',
            name='Size',
        ),
        migrations.RemoveField(
            model_name='land',
            name='pub_date',
        ),
    ]
