# Generated by Django 3.1.5 on 2021-01-08 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0002_bid_bidding_like_on_sale_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='land_id',
        ),
        migrations.AddField(
            model_name='bid',
            name='bidding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lands.bidding'),
        ),
    ]
