# Generated by Django 3.1.4 on 2021-01-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0002_auto_20210104_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='Description',
            field=models.TextField(default='Land description'),
        ),
        migrations.AddField(
            model_name='land',
            name='Likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='Location',
            field=models.CharField(default='location', max_length=100),
        ),
        migrations.AddField(
            model_name='land',
            name='Negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='land',
            name='Price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='Size',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
