# Generated by Django 3.1.5 on 2021-01-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0003_auto_20210104_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='land',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='Likes',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='Negotiable',
            new_name='negotiable',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='Size',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='land',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='land',
            name='id',
        ),
        migrations.AddField(
            model_name='land',
            name='land_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
