# Generated by Django 3.1.5 on 2021-01-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0004_auto_20210108_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
