# Generated by Django 3.1.5 on 2021-01-05 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0004_auto_20210105_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='land_owner',
            fields=[
                ('land_owner_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('land_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lands.land')),
            ],
        ),
    ]
