# Generated by Django 3.1.5 on 2021-01-05 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0005_land_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='land_owner',
            old_name='land_id',
            new_name='land',
        ),
    ]
