# Generated by Django 3.1.5 on 2021-01-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0005_land_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='location',
            field=models.TextField(default='Location not disclosed'),
        ),
    ]
