# Generated by Django 3.1.5 on 2021-01-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0006_auto_20210105_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='land_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='land_owner',
        ),
    ]
