# Generated by Django 3.1.5 on 2021-02-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0007_auto_20210128_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='town',
            field=models.TextField(default='Town not disclosed'),
        ),
    ]
