# Generated by Django 3.1.5 on 2021-01-08 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_message',
            fields=[
                ('admin_message_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
        ),
    ]
