# Generated by Django 3.1.5 on 2021-02-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210204_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
