# Generated by Django 3.1.5 on 2021-02-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210217_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='expert',
            fields=[
                ('expert_id', models.AutoField(primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
