# Generated by Django 3.1.5 on 2021-02-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/expert_logos/% Y/% m/% d/'),
        ),
    ]
