# Generated by Django 3.1.5 on 2021-02-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_expert_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
